export const ACTION_TYPES = {
  SET_TIME: "SET_TIME",
  SET_LOTS: "SET_LOTS",
  SET_LOT_PRICE: "SET_LOT_PRICE",
  SET_LOT_FAVORITE: "SET_LOT_FAVORITE",
  SET_LOT_UNFAVORITE: "SET_LOT_UNFAVORITE",
  SET_LOCATION: "SET_LOCATION",
} as const;
